In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore",category=FutureWarning)
warnings.filterwarnings("ignore")

In [2]:
df=pd.read_csv(r"C:\Users\sharo\Desktop\AI\AI Library\SupervisedLearning\SimpleLinearRegressing\homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
x_df=df.drop("price",axis=1)
y_df=df.drop(["area"],axis=1)

In [4]:
lr=LinearRegression()
lr.fit(x_df,y_df)

LinearRegression()

In [5]:
lr.coef_

array([[135.78767123]])

In [6]:
lr.intercept_

array([180616.43835616])

#### creating pickle file

In [7]:
import pickle

In [8]:
# ippo binary file create aayittundakum ee folderil

with open("lr_model",'wb') as file:
    pickle.dump(lr,file)




In [9]:
# how to load

with open("lr_model",'rb') as file:
    np = pickle.load(file)

In [10]:
np.coef_

array([[135.78767123]])

### creating by joblib

In [11]:
import joblib

In [12]:
joblib.dump(lr,"job_lib_model")


['job_lib_model']

In [13]:
mj = joblib.load("job_lib_model")

In [14]:
mj.coef_

array([[135.78767123]])

####  creating a json file by with open

In [15]:
import json

sample={
    "name":"sharon",
    "location":"Kochi"

}

json_object=json.dumps(sample)   # ippo sample json object aayi

In [16]:
with open("sample_json","w") as file:   # ippo file create aakum,,,,ithil b kodukkatha karyam file il string mathrame ullu but incase of pickle athil pala datatype und
    file.write(json_object)

In [17]:
with open("sample_json","r") as file:
    new = json.load(file)

In [18]:
new

{'name': 'sharon', 'location': 'Kochi'}