In [1]:
# install python package - NumPy

In [2]:
#pip install numpy

In [ ]:
import numpy as np

: 

In [3]:
myList=[1,2,3,4,5]

In [4]:
print(myList)

[1, 2, 3, 4, 5]


In [5]:
type(myList)

list

In [5]:
#dir(np)

In [6]:
#help(np)

In [7]:
arr=np.array(myList)

In [8]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
type(arr)

numpy.ndarray

In [10]:
arr.size

5

In [11]:
arr.shape

(5,)

In [12]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]

arr=np.array([list1,list2,list3])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [14]:
type(arr)  

numpy.ndarray

In [15]:
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [29]:
list=[1,2,3,4,5]
arr=np.array(list)

In [19]:
print(arr[0])

1


In [20]:
print(arr[1])

2


In [21]:
print("third element is:",arr[2],"and","fourth element is:",arr[3])

third element is: 3 and fourth element is: 4


In [11]:
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]

arr=np.array([list1,list2,list3])
print(arr)


[[[1 2 3 4 5]
  [2 3 4 5 6]
  [3 4 5 6 7]]]


In [42]:
arr[1,1]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [24]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [41]:
arr[1,3]

5

In [27]:
val=np.array([[1,2,3],[4,5,6]])  #create a 2d array....array kodukkumbol square bracket take care
print("printing the variable:",val,"\n")
print("shape of the variable:",val.shape,"\n")
print("size of the variable:",val.size,"\n")
print("first row first colomn:",val[0,0],"\n")
print("second row third colomn:",val[1,2],"\n")

printing the variable: [[1 2 3]
 [4 5 6]] 

shape of the variable: (2, 3) 

size of the variable: 6 

first row first colomn: 1 

second row third colomn: 6 



In [47]:
# numpy slicing


myList=[1,2,3,4,5,6,7,8,9,10]
arr=np.array(myList)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
#arr [start:end]   it will print end-1 elements
arr[0:3]

array([1, 2, 3])

In [19]:
arr[0:-1]

array([1, 2, 3, 4, 5])

In [26]:
#arr[0:5]
arr[:4]

array([1, 2, 3, 4])

In [48]:
#arr[-4:-1]

arr[:]

#arr[-3:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
#we need to print starting to end by difference two

arr[::2]

array([1, 3, 5, 7, 9])

In [42]:
#slicing 2d array

list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]

arr=np.array([list1,list2,list3])
print(arr)





[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [43]:
arr[0:2,1:4]    #arr[row start:end,colom start:end]

array([[2, 3, 4],
       [3, 4, 5]])

In [45]:
arr.shape

(3, 5)

In [52]:
#Arange(a range) function

np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [54]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
#LinSpace  normal distribution follow cheyyunna array list cheyyum

np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [57]:
#data type  ,,,kude varunna number athin ethra memory space use cheythittund
arr=np.array([1,2,3,4])
arr=np.array(["banaa","apple"])

print(arr.dtype)

<U5


In [6]:
import numpy as np
arr=np.array([1,2,3,4],dtype='S')  #here we forcefully changing the datatype of array thats why there is a b in result it shows that there is a forced change
print(arr)
print(arr.dtype)  #now the dataype is string 's',dont mind the number after that

[b'1' b'2' b'3' b'4']
|S1


In [7]:
arr

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [9]:
# array math

x=np.array([[1,2,3],[2,3,4]])
y=np.array([[3,4,5],[2,2,3]])


In [10]:
x+y

array([[4, 6, 8],
       [4, 5, 7]])

In [13]:
np.add(x,y)  #ingane ella operation cheyyan pattum

array([[4, 6, 8],
       [4, 5, 7]])

In [14]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [0.69314718, 1.09861229, 1.38629436]])

In [15]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.90929743,  0.14112001, -0.7568025 ]])

In [18]:
x = np.array([[1.5,2.5],[3.1,4.9]], dtype=np.float64)
print(x)

[[1.5 2.5]
 [3.1 4.9]]


In [21]:
np.floor(x)  #similar to floor division
np.ceil(x)   #next whole number
np.round(x)  #round according to .5

array([[2., 2.],
       [3., 5.]])

In [22]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
z = np.array([[9,10],[11,12]])


x

In [23]:
x

array([[1, 2],
       [3, 4]])

In [24]:
np.sum(x,axis=0) #column and row vise sum ;;;;;   0==colom and 1==row

array([4, 6])

In [25]:
np.sum(x,axis=1)

array([3, 7])

In [3]:
#Numpy array copy vs view
import numpy as np
arr=np.array([1,2,3,4])
x=arr



In [4]:
print(arr)
print(x)


[1 2 3 4]
[1 2 3 4]


In [5]:
arr[1]=100
print(arr)  #it will chang both values
print(x)

[  1 100   3   4]
[  1 100   3   4]


In [8]:
arr=np.array([1,2,3,4])
x=arr.copy()


In [9]:
print(arr)
print(x)

[1 2 3 4]
[1 2 3 4]


In [10]:
arr[1]=200

In [11]:
print(arr)
print(x)  #there will be no change in the first copy

[  1 200   3   4]
[1 2 3 4]


In [12]:
np.arange(18)  #array define cheyyunnathin pakaram ith kodutha mathi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [13]:
np.arange(2,18)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [14]:
arr=np.arange(18)
arr_new=arr.reshape(3,6)  #1d to 2d

In [15]:
print(arr_new)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [18]:
#flatterning the array means 2d to 1d

arr_new=arr.reshape(-1)
print(arr_new)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [3]:
#conctination
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v=np.concatenate((x,y))

In [4]:
v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
#iterating array
arr=np.arange(1,7).reshape(3,2)
for x in arr:
    print(x)

1
2
3
4
5
6


In [15]:
import numpy as np
list1=[1,2,3,4,5]
list2=[2,3,4,5,6]
list3=[3,4,5,6,7]
arr=np.array([list1,list2,list3]).sum()
print(arr)


60
